# 服务端口配置
server:
  port: 8801

# 注册中心配置
eureka:
  client:
    service-url:
      #      defaultZone: http://user:password@localhost:8761/eureka
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

# Spring Boot/Cloud配置
spring:
  application:
    name: sawako-service-user
  # 数据库连接信息
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sawako?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: root
  # Spring Boot Admin控制台
  boot:
    admin:
      client:
        url: http://localhost:8769
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    config:
      uri: http://localhost:8888