# 服务端口配置
server:
  port: 8761

# 注册中心配置
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
#      defaultZone: http://user:password@localhost:8761/eureka
      defaultZone: http://localhost:8761/eureka

# Spring Boot/Cloud配置
spring:
  application:
    name: sawako-registry-eureka
  # Spring Boot Admin控制台
  boot:
    admin:
      client:
        url: http://localhost:8769


